### ISSUE TITLE
[BUG] - All animations causing black canvas issue. 

### ISSUE THREAD

**Issue by silversiren1101** [fantasycalendar/FoundryVTT-Sequencer#348] opened 2024-10-26 00:59 UTC
**Describe the bug**
Whenever an animation of some kind that uses Sequencer and (I think) a sprite anchor is invoked, the entire canvas goes black. Refreshing is the only way to fix. Disabled all animation related modules (Dice so Nice, Animated Animations, etc) and issue is resolved.

**To Reproduce**
1. Load into a world that uses Sequencer and one or more modules that use it, such as Dice so Nice or Animated Animations.
2. Trigger an animation in the game canvas that uses Sequencer, that is looking for a sprite to center it on (I think)?
3. Game canvas should go back.

**Expected behavior**
The game canvas should stay visible and the animation should play as intended.

**Screenshots**
![image](https://github.com/user-attachments/assets/effa74b7-6a86-40c8-90ea-4c93b5a13dc0)

**Setup:**
 - Foundry Version: 12.331
 - System Version: PF2e 6.5.0
 - Sequencer Version: 3.4.1
 - Browser & version: Firefox 131.0.3

**Active modules:**
 - Sequencer
 - socketlib
 - Animated Animations
 - Dice So Nice

**Comment by Haxxer** [comment] 2024-10-26 07:45
Duplicate of #347

**Closed by Haxxer** 2024-10-26 07:45 UTC
